@startuml Subscription State Machine
title Subscription State Machine
hide empty description

[*] --> CREATED
CREATED: Criado
CREATED --> PROVIDER_SUBSCRIPTION_CREATED
PROVIDER_SUBSCRIPTION_CREATED: Criada no provedor
PROVIDER_SUBSCRIPTION_CREATED --> ACTIVE
ACTIVE: Ativa
ACTIVE --> PROVIDER_SUBSCRIPTION_CANCELED
PROVIDER_SUBSCRIPTION_CANCELED: Cancelada no provedor
PROVIDER_SUBSCRIPTION_CANCELED --> CANCELED
CANCELED: Cancelada
ACTIVE --> [*]
CANCELED --> [*]
@enduml
