@startuml Transaction State Machine
title Transaction State Machine
hide empty description

[*] --> CREATED
CREATED: Pagamento pendente
CREATED --> APPROVED: REFUND
CREATED --> APPROVED: SPLIT
CREATED --> APPROVED: WITHDRAW
State PROVIDER {
  CREATED --> PROVIDER_USER_CREATED: PURCHASE
  CREATED --> PROVIDER_USER_CREATED: SUBSCRIPTION
  CREATED --> PROVIDER_USER_CREATED: P2P
  CREATED --> PROVIDER_USER_CREATED: DEPOSIT
  APPROVED --> PROVIDER_USER_CREATED
  PROVIDER_USER_CREATED: Registro do usuário
  PROVIDER_USER_CREATED --> PROVIDER_PAYMENT_CREATED
  PROVIDER_PAYMENT_CREATED: Pagamento pendente
  state PROVIDER_PAYMENT_PROCESS <<choice>>
  PROVIDER_PAYMENT_CREATED --> PROVIDER_PAYMENT_PROCESS
  PROVIDER_PAYMENT_PROCESS --> PROVIDER_PAYMENT_PAID: Sucesso
  PROVIDER_PAYMENT_PAID: Pagamento realizado
  PROVIDER_PAYMENT_PROCESS --> PROVIDER_PAYMENT_FAILED: Falha
  PROVIDER_PAYMENT_FAILED: Falha no pagamento
}
APPROVED --> PAID: Pagamento Manual
PROVIDER_PAYMENT_PAID --> PAID
PAID --> [*]
PROVIDER_PAYMENT_FAILED --> FAILED
FAILED --> [*]
CREATED --> CANCELED: Requested\nby user
CREATED --> CANCELED: Rejected
CANCELED --> [*]
CREATED --> DELETED
DELETED --> [*]

@enduml
