@startuml Whitelabel State Machine
title Whitelabel State Machine
hide empty description

[*] --> CREATED
CREATED --> ACTIVE
CREATED: Criado
ACTIVE: Disponível
ACTIVE --> UNAVALIABLE
UNAVALIABLE: Indisponível
ACTIVE --> [*]
UNAVALIABLE --> [*]
@enduml
