export enum Whitelabel {
  DEFAULT = "default",
  FPASS = "fpass",
  FPASS_NEXT = "fpass-next",
  ALELO = "alelo",
  DFLIX = "dflix",
  HINODE = "hinode",
  PFIZER = "pfizer",
  FRSTFALCONI = "frstfalconi",
  OUROMODERNO = "ouromoderno",
  INSTITUTOCINEMA = "institutocinema",
  EVENTPLAY = "eventplay",
  ITAU_ION = "itau-ion",
  EMBRACLASS = "embraclass",
  GRUPOHDP = "grupohdp",
  AIA = "aia",
  VOOMP = "voomp",
}
